// Code generated by protoc-gen-go. DO NOT EDIT.
// source: conf.proto

package conf_grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FetchRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Ipaddr               string   `protobuf:"bytes,2,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
	Mac                  string   `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FetchRequest) Reset()         { *m = FetchRequest{} }
func (m *FetchRequest) String() string { return proto.CompactTextString(m) }
func (*FetchRequest) ProtoMessage()    {}
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b6ecbfc68e85c65, []int{0}
}

func (m *FetchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FetchRequest.Unmarshal(m, b)
}
func (m *FetchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FetchRequest.Marshal(b, m, deterministic)
}
func (m *FetchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FetchRequest.Merge(m, src)
}
func (m *FetchRequest) XXX_Size() int {
	return xxx_messageInfo_FetchRequest.Size(m)
}
func (m *FetchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FetchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FetchRequest proto.InternalMessageInfo

func (m *FetchRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *FetchRequest) GetIpaddr() string {
	if m != nil {
		return m.Ipaddr
	}
	return ""
}

func (m *FetchRequest) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *FetchRequest) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type Conf struct {
	Username             string    `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Button               []*Button `protobuf:"bytes,2,rep,name=button,proto3" json:"button,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Conf) Reset()         { *m = Conf{} }
func (m *Conf) String() string { return proto.CompactTextString(m) }
func (*Conf) ProtoMessage()    {}
func (*Conf) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b6ecbfc68e85c65, []int{1}
}

func (m *Conf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conf.Unmarshal(m, b)
}
func (m *Conf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conf.Marshal(b, m, deterministic)
}
func (m *Conf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conf.Merge(m, src)
}
func (m *Conf) XXX_Size() int {
	return xxx_messageInfo_Conf.Size(m)
}
func (m *Conf) XXX_DiscardUnknown() {
	xxx_messageInfo_Conf.DiscardUnknown(m)
}

var xxx_messageInfo_Conf proto.InternalMessageInfo

func (m *Conf) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Conf) GetButton() []*Button {
	if m != nil {
		return m.Button
	}
	return nil
}

type Button struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Button) Reset()         { *m = Button{} }
func (m *Button) String() string { return proto.CompactTextString(m) }
func (*Button) ProtoMessage()    {}
func (*Button) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b6ecbfc68e85c65, []int{2}
}

func (m *Button) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Button.Unmarshal(m, b)
}
func (m *Button) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Button.Marshal(b, m, deterministic)
}
func (m *Button) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Button.Merge(m, src)
}
func (m *Button) XXX_Size() int {
	return xxx_messageInfo_Button.Size(m)
}
func (m *Button) XXX_DiscardUnknown() {
	xxx_messageInfo_Button.DiscardUnknown(m)
}

var xxx_messageInfo_Button proto.InternalMessageInfo

func (m *Button) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Button) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*FetchRequest)(nil), "conf_grpc.FetchRequest")
	proto.RegisterType((*Conf)(nil), "conf_grpc.Conf")
	proto.RegisterType((*Button)(nil), "conf_grpc.Button")
}

func init() { proto.RegisterFile("conf.proto", fileDescriptor_0b6ecbfc68e85c65) }

var fileDescriptor_0b6ecbfc68e85c65 = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x69, 0x13, 0xa3, 0x99, 0x0a, 0xea, 0x20, 0xba, 0x14, 0x0f, 0x25, 0xa7, 0x7a, 0xc9,
	0x21, 0x7d, 0x83, 0x0a, 0xea, 0xc5, 0x4b, 0x5e, 0x40, 0xb6, 0xc9, 0x54, 0x0b, 0xdd, 0x0f, 0x37,
	0xb3, 0xe2, 0xe3, 0xcb, 0x6e, 0x97, 0x98, 0x93, 0xb7, 0xff, 0xc7, 0x30, 0xf3, 0x63, 0x00, 0x3a,
	0xa3, 0xf7, 0xb5, 0x75, 0x86, 0x0d, 0x96, 0x41, 0xbf, 0x7f, 0x38, 0xdb, 0x55, 0x0e, 0x2e, 0x9f,
	0x89, 0xbb, 0xcf, 0x96, 0xbe, 0x3c, 0x0d, 0x8c, 0x4b, 0xb8, 0xf0, 0x03, 0x39, 0x2d, 0x15, 0x89,
	0xd9, 0x6a, 0xb6, 0x2e, 0xdb, 0xd1, 0xe3, 0x1d, 0x14, 0x07, 0x2b, 0xfb, 0xde, 0x89, 0x79, 0x6c,
	0x92, 0xc3, 0x6b, 0xc8, 0x94, 0xec, 0x44, 0x16, 0xc3, 0x20, 0xf1, 0x01, 0x4a, 0x3e, 0x28, 0x1a,
	0x58, 0x2a, 0x2b, 0xf2, 0x98, 0xff, 0x05, 0xd5, 0x1b, 0xe4, 0x4f, 0x46, 0xef, 0xff, 0xbd, 0xf5,
	0x08, 0xc5, 0xce, 0x33, 0x1b, 0x2d, 0xe6, 0xab, 0x6c, 0xbd, 0x68, 0x6e, 0xea, 0x91, 0xb9, 0xde,
	0xc6, 0xa2, 0x4d, 0x03, 0x55, 0x03, 0xc5, 0x29, 0x41, 0x84, 0x9c, 0xe9, 0x87, 0xd3, 0xb2, 0xa8,
	0xf1, 0x16, 0xce, 0xbe, 0xe5, 0xd1, 0x53, 0x62, 0x3e, 0x99, 0x66, 0x0b, 0x8b, 0x80, 0xf0, 0x2a,
	0x75, 0x7f, 0x24, 0x87, 0x1b, 0x38, 0x7f, 0x21, 0x8e, 0x50, 0xf7, 0x93, 0x43, 0xd3, 0xcf, 0x2c,
	0xaf, 0x26, 0x45, 0x98, 0xdc, 0x15, 0xf1, 0x99, 0x9b, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xba,
	0xf6, 0x39, 0x3b, 0x5a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConfHandlerClient is the client API for ConfHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConfHandlerClient interface {
	GetConf(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*Conf, error)
}

type confHandlerClient struct {
	cc *grpc.ClientConn
}

func NewConfHandlerClient(cc *grpc.ClientConn) ConfHandlerClient {
	return &confHandlerClient{cc}
}

func (c *confHandlerClient) GetConf(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*Conf, error) {
	out := new(Conf)
	err := c.cc.Invoke(ctx, "/conf_grpc.ConfHandler/GetConf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfHandlerServer is the server API for ConfHandler service.
type ConfHandlerServer interface {
	GetConf(context.Context, *FetchRequest) (*Conf, error)
}

func RegisterConfHandlerServer(s *grpc.Server, srv ConfHandlerServer) {
	s.RegisterService(&_ConfHandler_serviceDesc, srv)
}

func _ConfHandler_GetConf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfHandlerServer).GetConf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/conf_grpc.ConfHandler/GetConf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfHandlerServer).GetConf(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ConfHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "conf_grpc.ConfHandler",
	HandlerType: (*ConfHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConf",
			Handler:    _ConfHandler_GetConf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conf.proto",
}
